// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `IIceStreamer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <IIceStreamer.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <IceUtil/Iterator.h>
#include <IceUtil/DisableWarnings.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 304
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 2
#       error Ice patch level mismatch!
#   endif
#endif

static const ::std::string __IceStreamer__BitmapProvider__getBitmap_name = "getBitmap";

static const ::std::string __IceStreamer__BitmapProvider__getSceneInfo_name = "getSceneInfo";

::Ice::Object* IceInternal::upCast(::IceStreamer::BitmapProvider* p) { return p; }
::IceProxy::Ice::Object* IceInternal::upCast(::IceProxy::IceStreamer::BitmapProvider* p) { return p; }

void
IceStreamer::__read(::IceInternal::BasicStream* __is, ::IceStreamer::BitmapProviderPrx& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::IceStreamer::BitmapProvider;
        v->__copyFrom(proxy);
    }
}

void
IceStreamer::SceneInfo::__write(::IceInternal::BasicStream* __os) const
{
    __os->write(width);
    __os->write(height);
    __os->write(draft);
    __os->write(transparentColor);
    __os->write(shadowsEnabled);
    __os->write(viewDistance);
    __os->write(shadowIntensity);
    __os->write(nbRayIterations);
    __os->write(backgroundColorR);
    __os->write(backgroundColorG);
    __os->write(backgroundColorB);
    __os->write(supportFor3DVision);
    __os->write(width3DVision);
    __os->write(renderBoxes);
}

void
IceStreamer::SceneInfo::__read(::IceInternal::BasicStream* __is)
{
    __is->read(width);
    __is->read(height);
    __is->read(draft);
    __is->read(transparentColor);
    __is->read(shadowsEnabled);
    __is->read(viewDistance);
    __is->read(shadowIntensity);
    __is->read(nbRayIterations);
    __is->read(backgroundColorR);
    __is->read(backgroundColorG);
    __is->read(backgroundColorB);
    __is->read(supportFor3DVision);
    __is->read(width3DVision);
    __is->read(renderBoxes);
}

void
IceStreamer::DepthOfFieldInfo::__write(::IceInternal::BasicStream* __os) const
{
    __os->write(enabled);
    __os->write(pointOfFocus);
    __os->write(strength);
    __os->write(iterations);
}

void
IceStreamer::DepthOfFieldInfo::__read(::IceInternal::BasicStream* __is)
{
    __is->read(enabled);
    __is->read(pointOfFocus);
    __is->read(strength);
    __is->read(iterations);
}

::IceStreamer::bytes
IceProxy::IceStreamer::BitmapProvider::getBitmap(::Ice::Float ex, ::Ice::Float ey, ::Ice::Float ez, ::Ice::Float dx, ::Ice::Float dy, ::Ice::Float dz, ::Ice::Float ax, ::Ice::Float ay, ::Ice::Float az, const ::IceStreamer::SceneInfo& scInfo, const ::IceStreamer::DepthOfFieldInfo& dofInfo, const ::Ice::Context* __ctx)
{
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__IceStreamer__BitmapProvider__getBitmap_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::IceStreamer::BitmapProvider* __del = dynamic_cast< ::IceDelegate::IceStreamer::BitmapProvider*>(__delBase.get());
            return __del->getBitmap(ex, ey, ez, dx, dy, dz, ax, ay, az, scInfo, dofInfo, __ctx);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::IceStreamer::BitmapProvider::begin_getBitmap(::Ice::Float ex, ::Ice::Float ey, ::Ice::Float ez, ::Ice::Float dx, ::Ice::Float dy, ::Ice::Float dz, ::Ice::Float ax, ::Ice::Float ay, ::Ice::Float az, const ::IceStreamer::SceneInfo& scInfo, const ::IceStreamer::DepthOfFieldInfo& dofInfo, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__IceStreamer__BitmapProvider__getBitmap_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __IceStreamer__BitmapProvider__getBitmap_name, __del, __cookie);
    try
    {
        __result->__prepare(__IceStreamer__BitmapProvider__getBitmap_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__getOs();
        __os->write(ex);
        __os->write(ey);
        __os->write(ez);
        __os->write(dx);
        __os->write(dy);
        __os->write(dz);
        __os->write(ax);
        __os->write(ay);
        __os->write(az);
        scInfo.__write(__os);
        dofInfo.__write(__os);
        __os->endWriteEncaps();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

::IceStreamer::bytes
IceProxy::IceStreamer::BitmapProvider::end_getBitmap(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __IceStreamer__BitmapProvider__getBitmap_name);
    ::IceStreamer::bytes __ret;
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
        }
    }
    ::IceInternal::BasicStream* __is = __result->__getIs();
    __is->startReadEncaps();
    ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*> _____ret;
    __is->read(_____ret);
    ::std::vector< ::Ice::Byte>(_____ret.first, _____ret.second).swap(__ret);
    __is->endReadEncaps();
    return __ret;
}

::IceStreamer::SceneInfo
IceProxy::IceStreamer::BitmapProvider::getSceneInfo(const ::Ice::Context* __ctx)
{
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__IceStreamer__BitmapProvider__getSceneInfo_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::IceStreamer::BitmapProvider* __del = dynamic_cast< ::IceDelegate::IceStreamer::BitmapProvider*>(__delBase.get());
            return __del->getSceneInfo(__ctx);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::IceStreamer::BitmapProvider::begin_getSceneInfo(const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__IceStreamer__BitmapProvider__getSceneInfo_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __IceStreamer__BitmapProvider__getSceneInfo_name, __del, __cookie);
    try
    {
        __result->__prepare(__IceStreamer__BitmapProvider__getSceneInfo_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__getOs();
        __os->endWriteEncaps();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

::IceStreamer::SceneInfo
IceProxy::IceStreamer::BitmapProvider::end_getSceneInfo(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __IceStreamer__BitmapProvider__getSceneInfo_name);
    ::IceStreamer::SceneInfo __ret;
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
        }
    }
    ::IceInternal::BasicStream* __is = __result->__getIs();
    __is->startReadEncaps();
    __ret.__read(__is);
    __is->endReadEncaps();
    return __ret;
}

const ::std::string&
IceProxy::IceStreamer::BitmapProvider::ice_staticId()
{
    return ::IceStreamer::BitmapProvider::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::IceStreamer::BitmapProvider::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::IceStreamer::BitmapProvider);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::IceStreamer::BitmapProvider::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::IceStreamer::BitmapProvider);
}

::IceProxy::Ice::Object*
IceProxy::IceStreamer::BitmapProvider::__newInstance() const
{
    return new BitmapProvider;
}

::IceStreamer::bytes
IceDelegateM::IceStreamer::BitmapProvider::getBitmap(::Ice::Float ex, ::Ice::Float ey, ::Ice::Float ez, ::Ice::Float dx, ::Ice::Float dy, ::Ice::Float dz, ::Ice::Float ax, ::Ice::Float ay, ::Ice::Float az, const ::IceStreamer::SceneInfo& scInfo, const ::IceStreamer::DepthOfFieldInfo& dofInfo, const ::Ice::Context* __context)
{
    ::IceInternal::Outgoing __og(__handler.get(), __IceStreamer__BitmapProvider__getBitmap_name, ::Ice::Normal, __context);
    try
    {
        ::IceInternal::BasicStream* __os = __og.os();
        __os->write(ex);
        __os->write(ey);
        __os->write(ez);
        __os->write(dx);
        __os->write(dy);
        __os->write(dz);
        __os->write(ax);
        __os->write(ay);
        __os->write(az);
        scInfo.__write(__os);
        dofInfo.__write(__os);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    ::IceStreamer::bytes __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.is();
        __is->startReadEncaps();
        ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*> _____ret;
        __is->read(_____ret);
        ::std::vector< ::Ice::Byte>(_____ret.first, _____ret.second).swap(__ret);
        __is->endReadEncaps();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

::IceStreamer::SceneInfo
IceDelegateM::IceStreamer::BitmapProvider::getSceneInfo(const ::Ice::Context* __context)
{
    ::IceInternal::Outgoing __og(__handler.get(), __IceStreamer__BitmapProvider__getSceneInfo_name, ::Ice::Normal, __context);
    bool __ok = __og.invoke();
    ::IceStreamer::SceneInfo __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.is();
        __is->startReadEncaps();
        __ret.__read(__is);
        __is->endReadEncaps();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

::IceStreamer::bytes
IceDelegateD::IceStreamer::BitmapProvider::getBitmap(::Ice::Float ex, ::Ice::Float ey, ::Ice::Float ez, ::Ice::Float dx, ::Ice::Float dy, ::Ice::Float dz, ::Ice::Float ax, ::Ice::Float ay, ::Ice::Float az, const ::IceStreamer::SceneInfo& scInfo, const ::IceStreamer::DepthOfFieldInfo& dofInfo, const ::Ice::Context* __context)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::IceStreamer::bytes& __result, ::Ice::Float ex, ::Ice::Float ey, ::Ice::Float ez, ::Ice::Float dx, ::Ice::Float dy, ::Ice::Float dz, ::Ice::Float ax, ::Ice::Float ay, ::Ice::Float az, const ::IceStreamer::SceneInfo& scInfo, const ::IceStreamer::DepthOfFieldInfo& dofInfo, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_ex(ex),
            _m_ey(ey),
            _m_ez(ez),
            _m_dx(dx),
            _m_dy(dy),
            _m_dz(dz),
            _m_ax(ax),
            _m_ay(ay),
            _m_az(az),
            _m_scInfo(scInfo),
            _m_dofInfo(dofInfo)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::IceStreamer::BitmapProvider* servant = dynamic_cast< ::IceStreamer::BitmapProvider*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->getBitmap(_m_ex, _m_ey, _m_ez, _m_dx, _m_dy, _m_dz, _m_ax, _m_ay, _m_az, _m_scInfo, _m_dofInfo, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        ::IceStreamer::bytes& _result;
        ::Ice::Float _m_ex;
        ::Ice::Float _m_ey;
        ::Ice::Float _m_ez;
        ::Ice::Float _m_dx;
        ::Ice::Float _m_dy;
        ::Ice::Float _m_dz;
        ::Ice::Float _m_ax;
        ::Ice::Float _m_ay;
        ::Ice::Float _m_az;
        const ::IceStreamer::SceneInfo& _m_scInfo;
        const ::IceStreamer::DepthOfFieldInfo& _m_dofInfo;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __IceStreamer__BitmapProvider__getBitmap_name, ::Ice::Normal, __context);
    ::IceStreamer::bytes __result;
    try
    {
        _DirectI __direct(__result, ex, ey, ez, dx, dy, dz, ax, ay, az, scInfo, dofInfo, __current);
        try
        {
            __direct.servant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

::IceStreamer::SceneInfo
IceDelegateD::IceStreamer::BitmapProvider::getSceneInfo(const ::Ice::Context* __context)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::IceStreamer::SceneInfo& __result, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::IceStreamer::BitmapProvider* servant = dynamic_cast< ::IceStreamer::BitmapProvider*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->getSceneInfo(_current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        ::IceStreamer::SceneInfo& _result;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __IceStreamer__BitmapProvider__getSceneInfo_name, ::Ice::Normal, __context);
    ::IceStreamer::SceneInfo __result;
    try
    {
        _DirectI __direct(__result, __current);
        try
        {
            __direct.servant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

::Ice::ObjectPtr
IceStreamer::BitmapProvider::ice_clone() const
{
    throw ::Ice::CloneNotImplementedException(__FILE__, __LINE__);
    return 0; // to avoid a warning with some compilers
}

static const ::std::string __IceStreamer__BitmapProvider_ids[2] =
{
    "::Ice::Object",
    "::IceStreamer::BitmapProvider"
};

bool
IceStreamer::BitmapProvider::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__IceStreamer__BitmapProvider_ids, __IceStreamer__BitmapProvider_ids + 2, _s);
}

::std::vector< ::std::string>
IceStreamer::BitmapProvider::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__IceStreamer__BitmapProvider_ids[0], &__IceStreamer__BitmapProvider_ids[2]);
}

const ::std::string&
IceStreamer::BitmapProvider::ice_id(const ::Ice::Current&) const
{
    return __IceStreamer__BitmapProvider_ids[1];
}

const ::std::string&
IceStreamer::BitmapProvider::ice_staticId()
{
    return __IceStreamer__BitmapProvider_ids[1];
}

::Ice::DispatchStatus
IceStreamer::BitmapProvider::___getBitmap(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.is();
    __is->startReadEncaps();
    ::Ice::Float ex;
    ::Ice::Float ey;
    ::Ice::Float ez;
    ::Ice::Float dx;
    ::Ice::Float dy;
    ::Ice::Float dz;
    ::Ice::Float ax;
    ::Ice::Float ay;
    ::Ice::Float az;
    ::IceStreamer::SceneInfo scInfo;
    ::IceStreamer::DepthOfFieldInfo dofInfo;
    __is->read(ex);
    __is->read(ey);
    __is->read(ez);
    __is->read(dx);
    __is->read(dy);
    __is->read(dz);
    __is->read(ax);
    __is->read(ay);
    __is->read(az);
    scInfo.__read(__is);
    dofInfo.__read(__is);
    __is->endReadEncaps();
    ::IceInternal::BasicStream* __os = __inS.os();
    ::IceStreamer::bytes __ret = getBitmap(ex, ey, ez, dx, dy, dz, ax, ay, az, scInfo, dofInfo, __current);
    if(__ret.size() == 0)
    {
        __os->writeSize(0);
    }
    else
    {
        __os->write(&__ret[0], &__ret[0] + __ret.size());
    }
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
IceStreamer::BitmapProvider::___getSceneInfo(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    __inS.is()->skipEmptyEncaps();
    ::IceInternal::BasicStream* __os = __inS.os();
    ::IceStreamer::SceneInfo __ret = getSceneInfo(__current);
    __ret.__write(__os);
    return ::Ice::DispatchOK;
}

static ::std::string __IceStreamer__BitmapProvider_all[] =
{
    "getBitmap",
    "getSceneInfo",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

::Ice::DispatchStatus
IceStreamer::BitmapProvider::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< ::std::string*, ::std::string*> r = ::std::equal_range(__IceStreamer__BitmapProvider_all, __IceStreamer__BitmapProvider_all + 6, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __IceStreamer__BitmapProvider_all)
    {
        case 0:
        {
            return ___getBitmap(in, current);
        }
        case 1:
        {
            return ___getSceneInfo(in, current);
        }
        case 2:
        {
            return ___ice_id(in, current);
        }
        case 3:
        {
            return ___ice_ids(in, current);
        }
        case 4:
        {
            return ___ice_isA(in, current);
        }
        case 5:
        {
            return ___ice_ping(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
IceStreamer::BitmapProvider::__write(::IceInternal::BasicStream* __os) const
{
    __os->writeTypeId(ice_staticId());
    __os->startWriteSlice();
    __os->endWriteSlice();
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
    Object::__write(__os);
#else
    ::Ice::Object::__write(__os);
#endif
}

void
IceStreamer::BitmapProvider::__read(::IceInternal::BasicStream* __is, bool __rid)
{
    if(__rid)
    {
        ::std::string myId;
        __is->readTypeId(myId);
    }
    __is->startReadSlice();
    __is->endReadSlice();
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
    Object::__read(__is, true);
#else
    ::Ice::Object::__read(__is, true);
#endif
}

// COMPILERFIX: Stream API is not supported with VC++ 6
#if !defined(_MSC_VER) || (_MSC_VER >= 1300)
void
IceStreamer::BitmapProvider::__write(const ::Ice::OutputStreamPtr&) const
{
    Ice::MarshalException ex(__FILE__, __LINE__);
    ex.reason = "type IceStreamer::BitmapProvider was not generated with stream support";
    throw ex;
}

void
IceStreamer::BitmapProvider::__read(const ::Ice::InputStreamPtr&, bool)
{
    Ice::MarshalException ex(__FILE__, __LINE__);
    ex.reason = "type IceStreamer::BitmapProvider was not generated with stream support";
    throw ex;
}
#endif

void 
IceStreamer::__patch__BitmapProviderPtr(void* __addr, ::Ice::ObjectPtr& v)
{
    ::IceStreamer::BitmapProviderPtr* p = static_cast< ::IceStreamer::BitmapProviderPtr*>(__addr);
    assert(p);
    *p = ::IceStreamer::BitmapProviderPtr::dynamicCast(v);
    if(v && !*p)
    {
        IceInternal::Ex::throwUOE(::IceStreamer::BitmapProvider::ice_staticId(), v->ice_id());
    }
}
